import Head from "next/head";
import Banner from "../component/Banner/Banner";
import styles from "../styles/Home.module.css";
import Navbar from "../component/nav/Navbar";
import Card from "../component/Card/Card";
import SectionCards from "../component/Card/Section-cards";
import { getVideos } from "../lib/videos";

export default function Home() {
  const disneyVideos = getVideos();

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar username="Oswaldo" />

      <Banner
        title="Clifford the red doc"
        subTitle="A very cute dog."
        imgUrl="/static/cliford.jpg"
      />
      <div className={styles.seccionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="large" />
      </div>

      <div className={styles.seccionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="medium" />
      </div>
    </div>
  );
}
